name: Simple CI pipeline

on:
  push:
    branches:
     - main
  
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Pirnt message
      run: echo "Code checkout sucessfully!"

    - name: List files
      run: ls -la
  test:
   needs: build
   runs-on: ubuntu-latest
  
   steps:
    - name: Run tests
      run: echo "Running tests"
  
  deploy:
   needs: test
   runs-on: ubuntu-latest
  
   steps:
    - name: Deploy step
      run: echo "Deploying application"

    - name: Deploy step 2
      run: echo "Deploying application step 2"