name: full beginner pipeline

on:
  push:
    branches:
      - main

env:
  GLOBAL_VAR: "Hello from global"

jobs:
  setup:
    runs-on: ubuntu_latest

    outputs:
       MY_NAME: ${{ steps.set-name.outputs.name}}

    steps:
      - name: set name
        id: set-name
        run: echo "name=Neli" >> $GITHUB_OUTPUT
  
  build: 
    needs: setup
    runs-on: ubuntu_latest

    env:
      NAME: ${{ needs.setup.outputs.MY_NAME}}

    steps:
      - name: print name
        run: echo "Building for $NAME"
    
  test:
    needs: build
    runs-on: ubuntu_latest

    steps:
      - name: Run test
        run: echo "running tests"
  
  deploy:
    needs: test
    runs-on: ubuntu_latest

    if: always()

    steps:
      - name: deploy
        run: echo "deploying"


        